// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'admin_enum.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'admin_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'admin_model.g.dart';

@freezed
class Admin with _$Admin {
  const factory Admin({
   required AdminType adminType
  }) = _Admin;

  factory Admin.fromJson(Map<String, Object?> json)
      => _$AdminFromJson(json);
}