// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:takafol/src/user_management/domain/app_user_type.dart';
import 'package:takafol/src/user_management/domain/user_info.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'notification_admin.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'notification_admin.g.dart';

@freezed
class NotificationAdmin with _$NotificationAdmin {
  const factory NotificationAdmin({
    String? id,
    required UserInformation admin,
    required String title,
    required String body,
    required DateTime date,
    required AccountType? accountType,
  }) = _NotificationAdmin;

  factory NotificationAdmin.fromJson(Map<String, Object?> json)
      => _$NotificationAdminFromJson(json);
}