// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:takafol/src/user_management/domain/user_info.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'notification_sender.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'notification_sender.g.dart';

@freezed
class NotificationSender with _$NotificationSender {
  const factory NotificationSender({
    required String title,
    String? id,
    required String body,
    required UserInformation senderInfo,
    required String reciveId,
  }) = _NotificationSender;

  factory NotificationSender.fromJson(Map<String, Object?> json)
      => _$NotificationSenderFromJson(json);
}