name: takafol
description: A new Flutter project.
# publish_to: 'karimkhatib' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  # sdk:'>=2.19.5 <3.0.0'

dependencies:
  audioplayers: ^5.1.0
  bot_toast: null
  cached_network_image: ^3.2.3
  cupertino_icons: null
  custom_refresh_indicator: ^2.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_osm_plugin: ^0.60.3
  flutter_riverpod: null
  flutter_screenutil: null
  flutter_sound: ^9.2.13
  flutter_sound_platform_interface: ^9.2.13
  flutter_svg: null
  freezed_annotation: null
  go_router: null
  image_picker: null
  json_annotation: null
  location: ^5.0.3
  lottie: null
  permission_handler: ^10.4.3
  reactive_date_time_picker: null
  reactive_file_picker: null
  reactive_flutter_typeahead: null
  reactive_forms: null
  reactive_phone_form_field: null
  reactive_pinput: null
  riverpod: null
  riverpod_annotation: null
  shared_preferences: null
  shimmer: ^3.0.0
  simple_speed_dial: null
  social_login_buttons: null
  supabase_flutter: ^1.10.14
  uuid: null

dev_dependencies:
  build_runner: ^2.3.3
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.6.2

  # the code generator
  riverpod_generator: null

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/json/
    - assets/fonts/
    - assets/png/
    - assets/svg/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
