// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'note_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'note_model.g.dart';

@freezed
class Note with _$Note {
  const factory Note({
     String? text,
     List<String>? voiceUrl,
     List<String>? imageUrl,
     
  }) = _Note;

  factory Note.fromJson(Map<String, Object?> json)
      => _$NoteFromJson(json);
}