// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzPETrJjuCquvmy3m4MSdCYrgW1hWpmos',
    appId: '1:882733031604:web:b2863a8ab0dac353db37e1',
    messagingSenderId: '882733031604',
    projectId: 'takafl21',
    authDomain: 'takafl21.firebaseapp.com',
    storageBucket: 'takafl21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTZ1e8D4CUIVmCohSNQk7AsLuwqCofSog',
    appId: '1:882733031604:android:44a9983640399e2cdb37e1',
    messagingSenderId: '882733031604',
    projectId: 'takafl21',
    storageBucket: 'takafl21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlWJWPpBGQXBETDefO5ZCgwZ0Tv-Ks2h4',
    appId: '1:882733031604:ios:a54facd4a4e0ba1bdb37e1',
    messagingSenderId: '882733031604',
    projectId: 'takafl21',
    storageBucket: 'takafl21.appspot.com',
    iosBundleId: 'com.takafol.io',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlWJWPpBGQXBETDefO5ZCgwZ0Tv-Ks2h4',
    appId: '1:882733031604:ios:a54facd4a4e0ba1bdb37e1',
    messagingSenderId: '882733031604',
    projectId: 'takafl21',
    storageBucket: 'takafl21.appspot.com',
    iosBundleId: 'com.takafol.io',
  );
}
