import 'package:equatable/equatable.dart';
import 'package:takafol/src/user_management/domain/app_user_model.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:takafol/src/user_management/domain/parse_server/app_user_pars.dart';

// required: associates our `main.dart` with the code generated by Freezed


enum AuthStatus {
  login,
  unAuth,
  verification,
  auth, //go to home
  signup,
  registration,
  loading,
  verify,
  waitingEmail,
}

class UserAuthState extends Equatable {
  final AuthStatus state;
  final AppUser? currentUser;
  final String? email;
  final String? uid;
  const UserAuthState({
    required this.state,
    this.currentUser,
    this.email,
    this.uid
  });

  @override
  List<Object?> get props => [state, currentUser];

  UserAuthState copyWith({
    AuthStatus? state,
    AppUser? currentUser,
      final String? email,
  final String? uid,
  }) {
    return UserAuthState(
      state: state ?? this.state,
      currentUser: currentUser ?? this.currentUser,
      email: email??this.email,
      uid: uid??this.uid
    );
  }
}
