// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:takafol/src/admin_management/domain/admin_model.dart';
import 'package:takafol/src/benefactor_management/domain/benefactor_model.dart';
import 'package:takafol/src/needy_mangement/domain/needy_model.dart';
import 'package:takafol/src/user_management/domain/app_user_type.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'app_user_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'app_user_model.g.dart';

@freezed
class AppUser with _$AppUser {
  const factory AppUser({
    String? id,
    required String firstName,
    required String lastName,
    String? secoundName,
    DateTime? birthday,
    required String username,
    required String password,
    String? email,
    double?  latitude ,
    double? longitude,
    String? bio,
    Needy? needy, 
    BenefactorModel? benefactorModel,
    Admin? admin,
    @Default(false) bool isOnline,
    required AccountType accountType,
    String? imageUrl,
    String? creatorId,
    String? token,
    @Default(true) bool isActive,


  }) = _AppUser;

  factory AppUser.fromJson(Map<String, Object?> json)
      => _$AppUserFromJson(json);
}