// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:takafol/src/user_management/domain/app_user_type.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_info.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_info.g.dart';

@freezed
class UserInformation with _$UserInformation {
  const factory UserInformation({
   String?id,
   String? name,
   AccountType? accountType,
   String? imageUrl,
   DateTime? birthDay,

   
  }) = _UserInformation;

  factory UserInformation.fromJson(Map<String, Object?> json)
      => _$UserInformationFromJson(json);
}