// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:takafol/src/chat_management/domain/message.dart';
import 'package:takafol/src/chat_management/domain/message_type.dart';
import 'package:takafol/src/user_management/domain/user_info.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'chat.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'chat.g.dart';

@freezed
class Chat with _$Chat{
  const factory Chat({
    String? id,
   required  UserInformation sender,
  required   UserInformation recive,
     Message? lastMessage,  



   
  }) = _Chat;

  factory Chat.fromJson(Map<String, Object?> json)
      => _$ChatFromJson(json);
}