// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:takafol/src/donations_mangement/domain/donation_enum.dart';
import 'package:takafol/src/user_management/domain/user_info.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'donation_status.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'donation_status.g.dart';

@freezed
class DonationStatus with _$DonationStatus{
  const factory DonationStatus({
   
    required DonationState name,
   
    //  UserInformation? needy,
    DateTime? createdDate,
  }) = _DonationStatus;

  factory DonationStatus.fromJson(Map<String, Object?> json)
      => _$DonationStatusFromJson(json);
}